version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: todo-app-agent-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app_agent
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 